require "ruby-ois"
require_relative "../../../lib/ruby-ogre.rb"

SWIG = 'swig'
SWIGFLAGS = "-ruby -c++ #{Ruby::Ogre::get_inc_flags} #{Ruby::Ois::get_inc_flags} -I#{Ruby::Ogre::get_top_path}/bindings/ogre/interface -I#{Ruby::Ois::get_top_path}/bindings/ois/interface  -autorename"

TARGET = 'ogrebites_wrap.cpp'

#puts SWIGFLAGS

task :default => "#{TARGET}"

file "#{TARGET}" => "ogrebites.i" do |t|
  sh "#{SWIG} #{SWIGFLAGS} -o  #{t.name} #{t.prerequisites[0]}"
end

task :clean do
  sh "rm -f #{TARGET}"
end

