SWIG = 'swig'

DEPS_DIR = "../../../deps/"
load "../../../deps/env.rb"


SWIGFLAGS = "-ruby -c++ #{OGRE_INC} #{OIS_INC} -autorename"

TARGET = 'ogrebites_wrap.cpp'

#puts SWIGFLAGS

task :default => "#{TARGET}"

file "#{TARGET}" => "ogrebites.i" do |t|
  sh "#{SWIG} #{SWIGFLAGS} -o  #{t.name} #{t.prerequisites[0]}"
end

task :clean do
  sh "rm -f #{TARGET}"
end

