require_relative "../../../lib/ruby-ogre.rb"

SWIG = 'swig'
SWIGFLAGS = "-ruby -c++ #{Ruby::Ogre::get_inc_flags} -I../src/ -autorename"

TARGET = 'ogre_wrap.cpp'

#puts SWIGFLAGS

task :default => "#{TARGET}"

file "#{TARGET}" => "ogre.i" do |t|
  sh "#{SWIG} #{SWIGFLAGS} -o  #{t.name} #{t.prerequisites[0]}"
end

task :clean do
  sh "rm -f #{TARGET}"
end

